server:
  port: 8088

spring:
  application:
    name: HMS_backend
  # Database Connection
  datasource:
    url: jdbc:postgresql://localhost:5432/HMS
    username: root
    password: root
  jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      properties:
          hibernate:
            format_sql: true
            show_sql: true

jwt:
  key: hms_346_493_key_@&
  expiration: 86400000